import AppKit

@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var ignoredChangeCount: Int?
    private var timer: Timer?
    private let onNewText: (String, String?, String?) -> Void

    private let privateTypes = Set([
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword"
    ])

    init(onNewText: @escaping (String, String?, String?) -> Void) {
        lastChangeCount = pasteboard.changeCount
        self.onNewText = onNewText
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func restore(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        ignoredChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }

    private func checkClipboard() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        if ignoredChangeCount == currentCount {
            ignoredChangeCount = nil
            return
        }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard privateTypes.isDisjoint(with: types) else { return }
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }
        let sourceApp = NSWorkspace.shared.frontmostApplication
        onNewText(text, sourceApp?.localizedName, sourceApp?.bundleIdentifier)
    }
}
